Repository aps-8id-dys/ipython-8idiuser, pull requests merged in 2020-10, with the labels that each got.

#236 handle jammed acquires (retry & continue)
  profile_bluesky/startup/instrument/plans/xpcs_acquire.py
  profile_bluesky/startup/instrument/utils/countdown.py
  profile_bluesky/startup/instrument/utils/emails.py
Labels: bug

#238 Set default timeout on EpicsSignalBase
  profile_bluesky/startup/instrument/framework/initialize.py
Labels: task

#239 Adding `move_pind4_in/out` in `pre_align/post_align`
  profile_bluesky/startup/instrument/plans/alignments.py
Labels: enhancement

#241 get control of that shutter in sb()
  profile_bluesky/startup/instrument/plans/alignments.py
Labels: bug
